Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/9"
  config.vm.box_version = "9.2.20230513"
  config.vm.network "private_network", ip: "192.168.56.10"

   config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end

  #   config.vm.provision "ansible" do |ansible|
  # ansible_local: required for windows hosts
  config.vm.provision "ansible_local" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "playbook.yml"
#   ansible.install_mode = "pip"
#   ansible.version = "7.6.0"
  end
end